name = "ai-oekaki-api"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[env.production]
name = "ai-oekaki-api"

[vars]
GOOGLE_GENAI_MODEL_NAME = "gemini-2.5-flash-lite"
IMAGEN_MODEL_NAME = "imagen-4.0-fast-generate-001"

[env.production.vars]
GOOGLE_GENAI_MODEL_NAME = "gemini-2.5-flash-lite"
IMAGEN_MODEL_NAME = "imagen-4.0-fast-generate-001"

[env.production.assets]
directory = "../web/dist"
binding = "ASSETS"

[dev]
ip = "0.0.0.0"
port = 8787
